# Generated by Django 3.2.16 on 2022-12-01 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 6, 39, 25, 983604)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 6, 39, 25, 985608)),
        ),
    ]
