# Generated by Django 3.2.16 on 2022-12-01 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221201_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 7, 34, 12, 961001)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 7, 34, 12, 961001)),
        ),
    ]
